In [1]:
import pandas as pd
import json 
import sys
import os

import pandas as pd
import numpy as np
from sklearn.cluster import KMeans
import pickle
from collections import defaultdict
import sklearn

In [63]:
def get_vec_string(lang_emb):
    vec = list(lang_emb)
    vec_str = ['%.9f' % val for val in vec]
    vec_str = " ".join(vec_str)
    return vec_str

In [3]:
datafile = "../data/URIEL/features.npz"

In [21]:
learned=np.load( "../data/URIEL/learned.npy", allow_pickle=True)

In [36]:
learned_dict = learned.item()

In [53]:
lang_size = len(learned_dict.keys())
lang_emb = learned_dict["mmo"].shape[0]
lang_size, lang_emb

(1018, 512)

In [64]:
writer = open("../data/URIEL/learned_embeddings", "w")
writer.write(f"{lang_size} {lang_emb}\n")
for lang in learned_dict["langs"]:
    lang_vec = learned_dict[lang]
    writer.write(lang + " ")
    vec_str= get_vec_string(lang_vec)
    writer.write(vec_str+'\n')

In [67]:
langs = list(learned_dict["langs"])
langs

['nhy',
 'wbp',
 'dgc',
 'aia',
 'aim',
 'aii',
 'ztq',
 'blw',
 'dgr',
 'blz',
 'xav',
 'dgz',
 'kjh',
 'mco',
 'lhu',
 'xnn',
 'kjb',
 'kje',
 'lom',
 'dhg',
 'ibo',
 'lhi',
 'iba',
 'zty',
 'lac',
 'tgp',
 'rmy',
 'lam',
 'mxb',
 'laj',
 'ctu',
 'lav',
 'rmc',
 'lat',
 'rme',
 'mxq',
 'lug',
 'cta',
 'mxt',
 'rmo',
 'rmn',
 'pag',
 'kmu',
 'ngp',
 'ngu',
 'kms',
 'kmm',
 'kmo',
 'kmh',
 'pwg',
 'kmk',
 'ngc',
 'tha',
 'tih',
 'msc',
 'plt',
 'plu',
 'bqc',
 'plw',
 'kxw',
 'hla',
 'ary',
 'cjo',
 'bqj',
 'arb',
 'nph',
 'npo',
 'npl',
 'cjv',
 'arn',
 'arl',
 'nya',
 'qub',
 'ksf',
 'mjw',
 'tmd',
 'snd',
 'nyn',
 'ksr',
 'kss',
 'ksp',
 'pes',
 'cuc',
 'mjc',
 'ese',
 'jam',
 'wbm',
 'maa',
 'maf',
 'sxb',
 'mhx',
 'maj',
 'huv',
 'huu',
 'yua',
 'hus',
 'jac',
 'mam',
 'cme',
 'maq',
 'mav',
 'mau',
 'maz',
 'jav',
 'hub',
 'yut',
 'dhm',
 'esk',
 'omw',
 'tur',
 'bgs',
 'tui',
 'tuo',
 'qul',
 'tuc',
 'quh',
 'lww',
 'tuf',
 'tue',
 'guo',
 'aeu',
 'wmt',
 'aey',
 'aeb',
 'tbk',


In [68]:
with open("../data/URIEL/uriel_learned_langs.json", "w") as f:
    json.dump(langs,f)

In [ ]:
list(learned_dict["mmo"])

In [4]:
features = np.load(datafile)

In [48]:
list(features.keys())

['feats', 'data', 'sources', 'langs']

In [50]:
features["langs"]

array(['aaa', 'aab', 'aac', ..., 'zyp', 'zza', 'zzj'], dtype='<U3')

In [9]:
FEATURE_SETS_DICT = {
    
    "syntax_wals" : ( "features.npz", "WALS", "S_" ),
    "phonology_wals": ( "features.npz", "WALS", "P_" ),
    "syntax_sswl" : ( "features.npz", "SSWL", "S_" ),
    "syntax_ethnologue": ( "features.npz", "ETHNO", "S_" ),
    "phonology_ethnologue" : ( "features.npz", "ETHNO", "P_" ),
    "inventory_ethnologue" : ( "features.npz", "ETHNO", "INV_" ),
    "inventory_phoible_aa" : ( "features.npz", "PHOIBLE_AA", "INV_" ),
    "inventory_phoible_gm" : ( "features.npz", "PHOIBLE_GM", "INV_" ),
    "inventory_phoible_saphon" : ( "features.npz", "PHOIBLE_SAPHON", "INV_"),
    "inventory_phoible_spa" : ( "features.npz", "PHOIBLE_SPA", "INV_" ),
    "inventory_phoible_ph" : ( "features.npz", "PHOIBLE_PH", "INV_" ),
    "inventory_phoible_ra" : ( "features.npz", "PHOIBLE_RA", "INV_" ),
    "inventory_phoible_upsid" : ( "features.npz", "PHOIBLE_UPSID", "INV_" ),
    "syntax_knn" : ( "feature_predictions.npz", "predicted", "S_" ),
    "phonology_knn" : ( "feature_predictions.npz", "predicted", "P_" ),
    "inventory_knn" : ( "feature_predictions.npz", "predicted", "INV_" ),
    "syntax_average" : ( "feature_averages.npz", "avg", "S_" ),
    "phonology_average" : ( "feature_averages.npz", "avg", "P_" ),
    "inventory_average" : ( "feature_averages.npz", "avg", "INV_" ),
    "fam" : ( "family_features.npz", "FAM", ""),
    "id" : ( "family_features.npz", "ID", ""),
    "geo" : ( "geocoord_features.npz", "GEOCOORDS", ""),
    "learned" : ( "learned.npy", "learned", "LEARNED_")
    
}

In [2]:
os.getcwd()

'/Users/yiyichen/Documents/experiments/ColexGraph/notebooks'

In [3]:
cd ../

/Users/yiyichen/Documents/experiments/ColexGraph


In [4]:
os.getcwd()

'/Users/yiyichen/Documents/experiments/ColexGraph'

In [5]:
from src.feature_prediction.dataset import Dataset

In [6]:
dataset= Dataset(100)

[  5.66666667  33.91666667 -29.         ...  -8.5         56.
  27.5       ] [  -4.58333333   35.5         -61.         ...  179.16666667   49.5
 -108.        ]
feature: Abidji,  -> column id: 1
feature: Kwa,  -> column id: 2
feature: Niger-Congo,  -> column id: 3
feature: 2 Red/yellow,  -> column id: 60
feature: 2 3.5,  -> column id: 75
feature: 2 4.5-5.5,  -> column id: 85
feature: 2 Green/blue,  -> column id: 94
feature: 23,  -> column id: 189
feature: Arabic (Beirut),  -> column id: 1
feature: Semitic,  -> column id: 2
feature: Afro-Asiatic,  -> column id: 3
feature: 1 Trochaic,  -> column id: 36
feature: 1 No fixed stress,  -> column id: 51
feature: 4 Long vowel or coda consonant,  -> column id: 103
feature: 4 Right-oriented: One of the last three,  -> column id: 177
feature: 15,  -> column id: 189
feature: Abipón,  -> column id: 1
feature: South Guaicuruan,  -> column id: 2
feature: Guaicuruan,  -> column id: 3
feature: 2 VO,  -> column id: 5
feature: 1 None,  -> column id: 6
fea

/opt/homebrew/Caskroom/miniforge/base/envs/colexgraph/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
/Users/yiyichen/Documents/experiments/ColexGraph/src/feature_prediction/dataset.py:68: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  new_dataset.append(np.array(new_line))
/Users/yiyichen/Documents/experiments/ColexGraph/src/feature_prediction/dataset.py:70: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when 


feature: 1 Identity,  -> column id: 99
feature: 1 No weight,  -> column id: 103
feature: 1 NegV,  -> column id: 104
feature: 2 Possessive suffixes,  -> column id: 106
feature: 1 Initial subordinator word,  -> column id: 108
feature: 2 Noun-Demonstrative,  -> column id: 109
feature: 4 No clause-final neg,  -> column id: 112
feature: 1 Associative same as additive plural,  -> column id: 118
feature: 1 Tense-aspect prefixes,  -> column id: 120
feature: 2 Case prefixes,  -> column id: 127
feature: 4 Negative word, unclear if verb or particle,  -> column id: 128
feature: 4 Mixed,  -> column id: 135
feature: 1 Separate word, no double negation	Word&NoDoubleNeg,  -> column id: 141
feature: 1 Question particle,  -> column id: 145
feature: 4 NegVOS,  -> column id: 154
feature: 1 Productive full and partial reduplication,  -> column id: 156
feature: 1 Plural prefix,  -> column id: 159
feature: 1 Initial,  -> column id: 161
feature: 1 No nominal plural,  -> column id: 163
feature: 4 VOS,  -> col

In [10]:
dataset.train_x

wals_code                  name                genus  \
0          abd                Abidji                  Kwa   
1          abe       Arabic (Beirut)              Semitic   
2          abi                Abipón     South Guaicuruan   
3          abk                Abkhaz  Northwest Caucasian   
4          abm               Alabama            Muskogean   
...        ...                   ...                  ...   
1120       tus             Tuscarora   Northern Iroquoian   
1121       tuv                 Tuvan               Turkic   
1122       tvl              Tuvaluan              Oceanic   
1123       tvo                 Tatar               Turkic   
1124       twe  Tarahumara (Western)          Tarahumaran   

                   family Distance_Contrasts_in_Demonstratives  \
0             Niger-Congo                                  NaN   
1            Afro-Asiatic                                  NaN   
2              Guaicuruan                                  NaN   
3     Northwest Caucasian                   2 Two-way contrast   
4               Muskogean                                  NaN   
...                   ...                                  ...   
1120            Iroquoian                   2 Two-way contrast   
1121               Altaic                                  NaN   
1122         Austronesian                                    ?   
1123               Altaic                                  NaN   
1124          Uto-Aztecan                                  NaN   

     Order_of_Object_and_Verb Presence_of_Uncommon_Consonants Numeral_Bases  \
0                         NaN                             NaN           NaN   
1                         NaN                             NaN           NaN   
2                           ?                          1 None           NaN   
3                        1 OV                               ?             ?   
4                         NaN                               ?     1 Decimal   
...                       ...                             ...           ...   
1120                        ?                             NaN           NaN   
1121                        ?                          1 None           NaN   
1122                        ?                             NaN           NaN   
1123                        ?                             NaN           NaN   
1124                     1 OV                             NaN     1 Decimal   

     Nonperiphrastic_Causative_Constructions          SOVNeg_Order  ...  \
0                                        NaN                   NaN  ...   
1                                        NaN                   NaN  ...   
2                                          ?                   NaN  ...   
3                                          ?  2 Suffix&NoDoubleNeg  ...   
4                                        NaN                   NaN  ...   
...                                      ...                   ...  ...   
1120                                       ?                   NaN  ...   
1121                                     NaN  2 Suffix&NoDoubleNeg  ...   
1122         2 Morphological but no compound                   NaN  ...   
1123                                     NaN                   NaN  ...   
1124                                     NaN                     ?  ...   

       Genitives,_Adjectives_and_Relative_Clauses  \
0                                             NaN   
1                                             NaN   
2                                             NaN   
3                         6 Highly differentiated   
4                                             NaN   
...                                           ...   
1120                                          NaN   
1121                                          NaN   
1122                                          NaN   
1123  4 Adjectives and relative clauses collapsed   
1124                                          

In [12]:
df = pd.concat([dataset.train_y, dataset.dev_x])

In [13]:
df

wals_code             name                genus               family  \
0        abd           Abidji                  Kwa          Niger-Congo   
1        abe  Arabic (Beirut)              Semitic         Afro-Asiatic   
2        abi           Abipón     South Guaicuruan           Guaicuruan   
3        abk           Abkhaz  Northwest Caucasian  Northwest Caucasian   
4        abm          Alabama            Muskogean            Muskogean   
..       ...              ...                  ...                  ...   
78       wob             Wobe                  Kru          Niger-Congo   
79       woi          Woisika         Greater Alor    Timor-Alor-Pantar   
80       wol         Woleaian              Oceanic         Austronesian   
81       wor           Worora            Worrorran            Worrorran   
82       wps        Wapishana           Wapishanan             Arawakan   

   Distance_Contrasts_in_Demonstratives Order_of_Object_and_Verb  \
0                                   NaN                      NaN   
1                                   NaN                      NaN   
2                                   NaN                     2 VO   
3                    2 Two-way contrast                     1 OV   
4                                   NaN                      NaN   
..                                  ...                      ...   
78                                  NaN                      NaN   
79                                  NaN                        ?   
80                                  NaN                     2 VO   
81                                  NaN                      NaN   
82                                  NaN                      NaN   

   Presence_of_Uncommon_Consonants               Numeral_Bases  \
0                              NaN                         NaN   
1                              NaN                         NaN   
2                           1 None                         NaN   
3                    4 Pharyngeals  2 Hybrid vigesimal-decimal   
4                           1 None                   1 Decimal   
..                             ...                         ...   
78                             NaN                         NaN   
79                               ?                         NaN   
80                             NaN                         NaN   
81                             NaN                         NaN   
82                          1 None                         NaN   

   Nonperiphrastic_Causative_Constructions          SOVNeg_Order  ...  \
0                                      NaN                   NaN  ...   
1                                      NaN                   NaN  ...   
2          2 Morphological but no compound                   NaN  ...   
3          2 Morphological but no compound  2 Suffix&NoDoubleNeg  ...   
4                                      NaN                   NaN  ...   
..                                     ...                   ...  ...   
78                                     NaN                   NaN  ...   
79                                     NaN                   NaN  ...   
80         2 Morphological but no compound                   NaN  ...   
81                                     NaN                   NaN  ...   
82                                     NaN                   NaN  ...   

   Genitives,_Adjectives_and_Relative_Clauses  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                     6 Highly differentiated   
4                                         NaN   
..                                        ...   
78                                        NaN   
79                                        NaN   
80                                        NaN   
81                                        NaN   
82                                        NaN   

   Pronominal_and_Adnomina

In [15]:
dataset.train_dataset

array([array([0, (1, 0), (2, 1), (3, 2), (60, 3), (75, 4), (85, 5), (94, 6),
              (189, 7)], dtype=object)                                      ,
       array([1, (1, 8), (2, 9), (3, 10), (36, 11), (51, 12), (103, 13),
              (177, 14), (189, 15)], dtype=object)                      ,
       array([2, (1, 16), (2, 17), (3, 18), (5, 19), (6, 20), (8, 21), (11, 22),
              (17, 23), (19, 24), (20, 25), (21, 26), (22, 27), (24, 28),
              (26, 29), (27, 30), (29, 31), (31, 32), (34, 33), (35, 34),
              (38, 35), (41, 36), (44, 37), (54, 38), (55, 39), (57, 40),
              (58, 41), (62, 42), (64, 43), (65, 44), (68, 45), (71, 46),
              (73, 47), (74, 48), (76, 49), (77, 50), (80, 51), (81, 52),
              (82, 53), (86, 54), (87, 55), (93, 56), (95, 57), (96, 58),
              (98, 59), (100, 60), (101, 61), (104, 62), (106, 63), (108, 64),
              (109, 65), (110, 66), (111, 67), (115, 68), (116, 69), (120, 70),
              

In [14]:
dataset.dev_x

wals_code        name                  genus             family  \
0        acl      Acholi                Nilotic    Eastern Sudanic   
1        agt  Anguthimri  Northern Pama-Nyungan       Pama-Nyungan   
2        agu   Aguacatec                  Mayan              Mayan   
3        ame       Amele                 Madang   Trans-New Guinea   
4        amx    Anamuxra                 Madang   Trans-New Guinea   
..       ...         ...                    ...                ...   
78       wob        Wobe                    Kru        Niger-Congo   
79       woi     Woisika           Greater Alor  Timor-Alor-Pantar   
80       wol    Woleaian                Oceanic       Austronesian   
81       wor      Worora              Worrorran          Worrorran   
82       wps   Wapishana             Wapishanan           Arawakan   

   Distance_Contrasts_in_Demonstratives Order_of_Object_and_Verb  \
0                                   NaN                     2 VO   
1                                   NaN                        ?   
2                                   NaN                      NaN   
3                                     ?                        ?   
4                                   NaN                     1 OV   
..                                  ...                      ...   
78                                  NaN                      NaN   
79                                  NaN                        ?   
80                                  NaN                     2 VO   
81                                  NaN                      NaN   
82                                  NaN                      NaN   

   Presence_of_Uncommon_Consonants Numeral_Bases  \
0                              NaN           NaN   
1                              NaN           NaN   
2                              NaN           NaN   
3                                ?           NaN   
4                              NaN           NaN   
..                             ...           ...   
78                             NaN           NaN   
79                               ?           NaN   
80                             NaN           NaN   
81                             NaN           NaN   
82                          1 None           NaN   

   Nonperiphrastic_Causative_Constructions           SOVNeg_Order  ...  \
0                                      NaN                    NaN  ...   
1                                      NaN                    NaN  ...   
2                                      NaN                    NaN  ...   
3          2 Morphological but no compound  4 Suffix&OptDoubleNeg  ...   
4                                      NaN                    NaN  ...   
..                                     ...                    ...  ...   
78                                     NaN                    NaN  ...   
79                                     NaN                    NaN  ...   
80         2 Morphological but no compound                    NaN  ...   
81                                     NaN                    NaN  ...   
82                                     NaN                    NaN  ...   

   Genitives,_Adjectives_and_Relative_Clauses  \
0                                         NaN   
1                                         NaN   
2                                         NaN   
3                                           ?   
4                                         NaN   
..                                        ...   
78                                        NaN   
79                                        NaN   
80                                        NaN   
81                                        NaN   
82                                        NaN   

   Pronominal_and_Adnominal_Demonstratives M_in_First_Person_Singular  \
0                                      NaN                        NaN   
1                                      NaN                        NaN   
2                      

In [11]:
dataset.train_dataset

array([array([0, (1, 0), (2, 1), (3, 2), (60, 3), (75, 4), (85, 5), (94, 6),
              (189, 7)], dtype=object)                                      ,
       array([1, (1, 8), (2, 9), (3, 10), (36, 11), (51, 12), (103, 13),
              (177, 14), (189, 15)], dtype=object)                      ,
       array([2, (1, 16), (2, 17), (3, 18), (5, 19), (6, 20), (8, 21), (11, 22),
              (17, 23), (19, 24), (20, 25), (21, 26), (22, 27), (24, 28),
              (26, 29), (27, 30), (29, 31), (31, 32), (34, 33), (35, 34),
              (38, 35), (41, 36), (44, 37), (54, 38), (55, 39), (57, 40),
              (58, 41), (62, 42), (64, 43), (65, 44), (68, 45), (71, 46),
              (73, 47), (74, 48), (76, 49), (77, 50), (80, 51), (81, 52),
              (82, 53), (86, 54), (87, 55), (93, 56), (95, 57), (96, 58),
              (98, 59), (100, 60), (101, 61), (104, 62), (106, 63), (108, 64),
              (109, 65), (110, 66), (111, 67), (115, 68), (116, 69), (120, 70),
              

In [7]:
dataset.global_feature_id

2742

In [8]:
dataset.all_features

array([  0,   1,   2, ..., 372,  92, 577])

In [11]:
dataset.feature_maps

[{},
 {'Abidji': 0,
  'Arabic (Beirut)': 8,
  'Abipón': 16,
  'Abkhaz': 95,
  'Alabama': 219,
  'Abun': 233,
  'Abui': 275,
  'Abaza': 291,
  'Acehnese': 295,
  'Aché': 327,
  'Achumawi': 333,
  'Achang': 344,
  'Acoma': 348,
  'Adang': 379,
  'Adioukrou': 387,
  'Adyghe (Abzakh)': 397,
  'Aleut (Eastern)': 400,
  'Arabic (Egyptian)': 407,
  'Arabic (Eastern Libyan)': 447,
  'Afrikaans': 450,
  'Leggbó': 459,
  'Agta (Central)': 466,
  'Agta (Dupaningan)': 482,
  'Aghem': 485,
  'Aghul': 495,
  'Angolar': 500,
  'Ahtna': 507,
  'Aikaná': 512,
  'Ainu': 517,
  'Aizi': 544,
  'Ajagbe': 547,
  'Akha': 553,
  'Aklanon': 556,
  'Akan': 560,
  'Arikara': 570,
  'Akawaio': 574,
  'Albanian': 579,
  'Alladian': 592,
  'Aleut': 593,
  'Alune': 601,
  'Alsea': 612,
  'Amahuaca': 617,
  'Amis': 624,
  'Amarakaeri': 629,
  'Ambae (Lolovoli Northeast)': 633,
  'Amo': 642,
  'Arabic (Moroccan)': 645,
  'Arabic (Modern Standard)': 655,
  'Amdo (Themchen)': 657,
  'Amuesha': 664,
  'Araona': 667,
  'A

In [9]:
dataset.train_dataset

array([array([0, (1, 0), (2, 1), (3, 2), (60, 3), (75, 4), (85, 5), (94, 6),
              (189, 7)], dtype=object)                                      ,
       array([1, (1, 8), (2, 9), (3, 10), (36, 11), (51, 12), (103, 13),
              (177, 14), (189, 15)], dtype=object)                      ,
       array([2, (1, 16), (2, 17), (3, 18), (5, 19), (6, 20), (8, 21), (11, 22),
              (17, 23), (19, 24), (20, 25), (21, 26), (22, 27), (24, 28),
              (26, 29), (27, 30), (29, 31), (31, 32), (34, 33), (35, 34),
              (38, 35), (41, 36), (44, 37), (54, 38), (55, 39), (57, 40),
              (58, 41), (62, 42), (64, 43), (65, 44), (68, 45), (71, 46),
              (73, 47), (74, 48), (76, 49), (77, 50), (80, 51), (81, 52),
              (82, 53), (86, 54), (87, 55), (93, 56), (95, 57), (96, 58),
              (98, 59), (100, 60), (101, 61), (104, 62), (106, 63), (108, 64),
              (109, 65), (110, 66), (111, 67), (115, 68), (116, 69), (120, 70),
              

In [27]:
dataset.train_dataset

array([array([0, (1, 0), (2, 1), (59, 2), (74, 3), (84, 4), (93, 5), (188, 6)],
             dtype=object)                                                     ,
       array([1, (1, 7), (2, 8), (35, 9), (50, 10), (102, 11), (176, 12),
              (188, 13)], dtype=object)                                  ,
       array([2, (1, 14), (2, 15), (4, 16), (5, 17), (7, 18), (10, 19), (16, 20),
              (18, 21), (19, 22), (20, 23), (21, 24), (23, 25), (25, 26),
              (26, 27), (28, 28), (30, 29), (33, 30), (34, 31), (37, 32),
              (40, 33), (43, 34), (53, 35), (54, 36), (56, 37), (57, 38),
              (61, 39), (63, 40), (64, 41), (67, 42), (70, 43), (72, 44),
              (73, 45), (75, 46), (76, 47), (79, 48), (80, 49), (81, 50),
              (85, 51), (86, 52), (92, 53), (94, 54), (95, 55), (97, 56),
              (99, 57), (100, 58), (103, 59), (105, 60), (107, 61), (108, 62),
              (109, 63), (110, 64), (114, 65), (115, 66), (119, 67), (120, 68),
     

In [51]:
dataset.feature_maps_int

[{},
 {0: 'Kwa',
  7: 'Semitic',
  14: 'South Guaicuruan',
  92: 'Northwest Caucasian',
  215: 'Muskogean',
  228: "North-Central Bird's Head",
  269: 'Greater Alor',
  287: 'Malayo-Sumbawan',
  318: 'Tupi-Guaraní',
  324: 'Palaihnihan',
  334: 'Burmese-Lolo',
  337: 'Keresan',
  386: 'Aleut',
  434: 'Germanic',
  442: 'Cross River',
  448: 'Greater Central Philippine',
  465: 'Bantoid',
  475: 'Lezgic',
  480: 'Creoles and Pidgins',
  487: 'Athapaskan',
  491: 'Aikaná',
  495: 'Ainu',
  521: 'Kru',
  542: 'Caddoan',
  545: 'Cariban',
  549: 'Albanian',
  568: 'Central Malayo-Polynesian',
  578: 'Alsea',
  582: 'Panoan',
  588: 'East Formosan',
  593: 'Harakmbet',
  597: 'Oceanic',
  605: 'Kainji',
  617: 'Bodic',
  623: "Yanesha'",
  625: 'Tacanan',
  643: 'West Chadic',
  644: 'Khoe-Kwadi',
  653: 'Nungish',
  659: 'Ge-Kaingang',
  668: 'Purus',
  681: 'Caribbean Arawakan',
  699: 'Armenian',
  729: 'Atayalic',
  732: 'Atakapa',
  737: 'Kunza',
  740: 'Eskimo',
  745: 'Avar-Andic-Tse

In [48]:
generator = dataset.batch_generator()

In [49]:
counter =0 
for d in generator:
    
    if counter <5:
        print(d)
        print("LOL", d[0][1])
        
        counter+=1
    

((array([ 506.,  981., 1044.,   89., 1072.,  182.,  139.,  115.,  910.,
       1108.,  242.,  651., 1103., 1058.,  601.,   18.,  969.,  820.,
       1158.,  158.,  950.,  584.,  160., 1193.,  623., 1106., 1144.,
        187.,  380.,  966.,  692.,  631.,  655., 1023.,  124., 1147.,
        343.,  557.,  578.,  362.,  846.,  511.,  898.,  982., 1001.,
       1028.,  436.,  957., 1036.,  891.,  717.,  998.,  655.,  440.,
        781.,  115., 1112., 1106.,  483.,  424.,  981.,  124.,  152.,
         41., 1135.,  390.,  314.,  357., 1037., 1181.,  483.,  331.,
        721., 1166., 1063.,  492.,  242.,  551.,  824.,  862.,  468.,
       1095.,  888.,  698.,  740.,  939.,  824.,  159.,  799.,  613.,
        606.,  526.,  778.,  591.,  370.,   44., 1033.,  931.,  799.,
         23.,  676.,  717.,  647.,   67.,  448.,  345.,  131.,  447.,
         52.,  816.,  400., 1090., 1055.,  953.,   98.,  267., 1046.,
        674.,  170.,  125.,   64.,  892.,  230.,  247., 1100., 1197.,
         34.,  215

KeyboardInterrupt: 